[book]
title = "rust-igraph 指南"
authors = ["Totoro-jam"]
language = "zh"
src = "src"

[output.html]
git-repository-url = "https://github.com/Totoro-jam/rust-igraph"
site-url = "/rust-igraph/book/zh/"
additional-js = ["theme/redirect-logo.js", "theme/lang-switcher.js"]

[output.html.fold]
enable = true
level = 1
