//! Hierarchical Stochastic Block Model benchmarks (ALGO-GN-011).
//!
//! Run: `cargo bench --bench bench_hsbm`. Results land under
//! `target/criterion/`. A snapshot of the baseline lives at
//! `.codefuse/tracking/perf/ALGO-GN-011.json`.
//!
//! Coverage:
//!   * `size_scaling/uniform_k2` — uniform variant, `m=50`, two
//!     equally-sized micro-clusters per macro, in-cluster `p=0.1`,
//!     between-cluster `p=0.02`, inter-macro `p=0.01`; sweep total
//!     `n ∈ {200, 1_000, 4_000}` (4, 20, 80 macros). Shows the
//!     `O(K · m² · c_max + macros² · p)` cost split.
//!   * `density_sweep/uniform_n2000_m50` — fixed `n=2_000, m=50`, sweep
//!     in-cluster `p ∈ {0.01, 0.05, 0.1, 0.3}`, between-cluster `0.005`,
//!     inter-macro `0.001`. Isolates the intra-macro sampler cost.
//!   * `p_sweep/uniform_n2000_m100` — fixed `n=2_000, m=100` (20
//!     macros), in/between-cluster fixed at `0.1`/`0.005`, sweep
//!     inter-macro `p ∈ {0.0, 0.01, 0.1, 0.5, 1.0}`. Shows how the
//!     macros² rectangular sampler scales.
//!   * `list_vs_uniform/n2000_k20` — same observable shape generated by
//!     `hsbm_game` and `hsbm_list_game` to verify the per-macro
//!     dispatcher overhead is small.
//!   * `list_irregular/n2000_jagged` — list variant with non-uniform
//!     macro sizes `m_list=[40, 80, 120, 160, 200, 240, 280, 320, 360,
//!     400]` (sums to `2_200`; we use `n=2_200`) and per-macro `rho`/`c`
//!     that vary in width. Stresses the heterogeneous code path.
//!
//! Throughput is reported in total vertices so wall-clock per element
//! is directly comparable to the other generator benches.

#![allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]

use criterion::{BenchmarkId, Criterion, Throughput, criterion_group, criterion_main};
use rust_igraph::{hsbm_game, hsbm_list_game};

fn bench_size_scaling_uniform(c: &mut Criterion) {
    let mut group = c.benchmark_group("hsbm_game/size_scaling/uniform_k2");
    let m: u32 = 50;
    let rho = vec![0.5, 0.5];
    let c_mat = vec![vec![0.1, 0.02], vec![0.02, 0.1]];
    let p_inter = 0.01;
    for n in [200u32, 1_000, 4_000] {
        group.throughput(Throughput::Elements(u64::from(n)));
        group.bench_with_input(BenchmarkId::from_parameter(n), &n, |b, _| {
            b.iter(|| hsbm_game(n, m, &rho, &c_mat, p_inter, 0xA5B0_1101).unwrap());
        });
    }
    group.finish();
}

fn bench_density_sweep(c: &mut Criterion) {
    let mut group = c.benchmark_group("hsbm_game/density_sweep/uniform_n2000_m50");
    let n: u32 = 2_000;
    let m: u32 = 50;
    let rho = vec![0.5, 0.5];
    let p_inter = 0.001;
    for p_in in [0.01_f64, 0.05, 0.1, 0.3] {
        let c_mat = vec![vec![p_in, 0.005], vec![0.005, p_in]];
        let label = format!("pin{p_in:.2}");
        group.throughput(Throughput::Elements(u64::from(n)));
        group.bench_with_input(BenchmarkId::from_parameter(label), &p_in, |b, _| {
            b.iter(|| hsbm_game(n, m, &rho, &c_mat, p_inter, 0xA5B0_1102).unwrap());
        });
    }
    group.finish();
}

fn bench_p_sweep(c: &mut Criterion) {
    let mut group = c.benchmark_group("hsbm_game/p_sweep/uniform_n2000_m100");
    let n: u32 = 2_000;
    let m: u32 = 100;
    let rho = vec![0.5, 0.5];
    let c_mat = vec![vec![0.1, 0.005], vec![0.005, 0.1]];
    for p_inter in [0.0_f64, 0.01, 0.1, 0.5, 1.0] {
        let label = format!("p{p_inter:.2}");
        group.throughput(Throughput::Elements(u64::from(n)));
        group.bench_with_input(BenchmarkId::from_parameter(label), &p_inter, |b, _| {
            b.iter(|| hsbm_game(n, m, &rho, &c_mat, p_inter, 0xA5B0_1103).unwrap());
        });
    }
    group.finish();
}

fn bench_list_vs_uniform(c: &mut Criterion) {
    let mut group = c.benchmark_group("hsbm_game/list_vs_uniform/n2000_k20");
    let n: u32 = 2_000;
    let m: u32 = 100;
    let rho = vec![0.5, 0.5];
    let c_mat = vec![vec![0.1, 0.02], vec![0.02, 0.1]];
    let p_inter = 0.01;

    group.throughput(Throughput::Elements(u64::from(n)));
    group.bench_function("uniform", |b| {
        b.iter(|| hsbm_game(n, m, &rho, &c_mat, p_inter, 0xA5B0_1104).unwrap());
    });

    let no_macros = (n / m) as usize;
    let m_list = vec![m; no_macros];
    let rho_list = vec![rho.clone(); no_macros];
    let c_list = vec![c_mat.clone(); no_macros];
    group.throughput(Throughput::Elements(u64::from(n)));
    group.bench_function("list_equivalent", |b| {
        b.iter(|| hsbm_list_game(n, &m_list, &rho_list, &c_list, p_inter, 0xA5B0_1105).unwrap());
    });
    group.finish();
}

fn bench_list_irregular(c: &mut Criterion) {
    let mut group = c.benchmark_group("hsbm_list_game/list_irregular/n2200_jagged");
    let m_list: Vec<u32> = vec![40, 80, 120, 160, 200, 240, 280, 320, 360, 400];
    let n: u32 = m_list.iter().sum();
    // Per-macro: alternate single-cluster, two-cluster, three-cluster.
    let mut rho_list: Vec<Vec<f64>> = Vec::with_capacity(m_list.len());
    let mut c_list: Vec<Vec<Vec<f64>>> = Vec::with_capacity(m_list.len());
    for (idx, _) in m_list.iter().enumerate() {
        match idx % 3 {
            0 => {
                rho_list.push(vec![1.0]);
                c_list.push(vec![vec![0.05]]);
            }
            1 => {
                rho_list.push(vec![0.5, 0.5]);
                c_list.push(vec![vec![0.1, 0.01], vec![0.01, 0.1]]);
            }
            _ => {
                let one_third = 1.0 / 3.0;
                rho_list.push(vec![one_third, one_third, 1.0 - 2.0 * one_third]);
                c_list.push(vec![
                    vec![0.2, 0.02, 0.005],
                    vec![0.02, 0.2, 0.02],
                    vec![0.005, 0.02, 0.2],
                ]);
            }
        }
    }
    let p_inter = 0.005;
    group.throughput(Throughput::Elements(u64::from(n)));
    group.bench_function("jagged", |b| {
        b.iter(|| hsbm_list_game(n, &m_list, &rho_list, &c_list, p_inter, 0xA5B0_1106).unwrap());
    });
    group.finish();
}

criterion_group!(
    benches,
    bench_size_scaling_uniform,
    bench_density_sweep,
    bench_p_sweep,
    bench_list_vs_uniform,
    bench_list_irregular,
);
criterion_main!(benches);
